config/routes.rb
RobotKarel::Application.routes.draw do
  resources :actors
  resources :simulations
  resources :maps

  match 'maps/:id/get_map' => 'maps#get_map'
  match 'maps/:id/save_map' => 'maps#save_map'
  match 'simulations/:simulation_id/get_map' => 'simulations#get_map'
  match 'simulations/:id/place_actors' => 'simulation#place_actors'
  match 'simulations/:id/save_sim' => 'simulations#save_sim'
  match 'simulations/:id/:count/simulate' => 'simulations#simulate'
  match 'simulations/:id/get_story' => 'simulations#get_story'
  match 'simulations/:id/watch' => 'simulations#watch'
  match 'simulations/:id/get_initial_state' => 'simulations#get_initial_state'
  match 'simulations/:id/get_actors' => 'simulations#get_actors'
  match 'actors/:id/get_properties' => 'actors#get_properties'

  match '/' => 'help#welcome'

  match ':controller(/:action(/:id(.:format)))'
end

app/models/simulation.rb
class Blacklist
  def initialize
    # Initialize banned words
    @blacklist = ["@actor", "@blacklist", "Blacklist", "Evaluator", "@source_code", "@static_code" ,"eval", "evaluate", "evaluate_static", "@static_code_errors", "@source_code_errors", "exit"]
  end

  def check(source_code)
    tokens = source_code.split(" ")
    errors = [];

    tokens.each do |token|
      @blacklist.each do |banned_word|
        if (token.include?(banned_word))
          errors.push << banned_word
        end
      end
    end

    return errors
  end
end


class Evaluator
  def initialize(source_code, static_code, actor)
    blacklist = Blacklist.new()
    @source_code = source_code
    @static_code = static_code
    @source_code_errors = blacklist.check(source_code)
    @static_code_errors = blacklist.check(static_code)
    @actor = actor
  end

  def evaluate
    begin
      if (@source_code_errors) != []
        msg = "Blacklisted words detected: "
        @source_code_errors.each do |error|
          msg = msg + error + " "
        end
        raise SyntaxError.new(msg)
      end

      eval(@source_code)
    rescue Exception => e
      log("Cannot evaluate source code because : " + e.message)
    end
  end

  def evaluate_static
    begin
      if (@static_code_errors) != []
        msg = "Blacklisted words detected: "
        @static_code_errors.each do |error|
          msg = msg + error + " "
        end
        raise SyntaxError.new(msg)
      end

      eval(@static_code)
    rescue Exception => e
      log("Cannot evaluate static code because : " + e.message)
    end
  end

  def get_directions
    return @actor.get_directions
  end

  def set_direction(direction_name)
    return @actor.set_direction(direction_name)
  end

  def get_position
    return @actor.get_position
  end

  def get_direction
    return @actor.get_direction
  end

  def move_possible?
    return @actor.move_possible?
  end

  def marker_present?
    return @actor.marker_present?
  end

  def pickup_marker
    return @actor.pickup_marker
  end

  def drop_marker
    return @actor.drop_marker
  end

  def log(message)
    return @actor.log(message)
  end

  def move
    return @actor.move
  end

end

class ActorImpl
  attr_reader :id, :name
  attr_accessor :marker, :position, :direction

  def initialize(position, direction, id, name, source_code, static_code, simulation)
    @position = position
    @direction = direction
    @id = id
    @name = name
    @evaluator = Evaluator.new(source_code, static_code, self)
    @simulation = simulation
    @messages = []
    @marker = nil
    @state = {}
    @state["move"] = false
    @state["pickup"] = false
    @state["drop"] = false
  end

  def set_state(name, value)
    @state[name] = value
  end

  def get_state(name)
    value = @state[name]
    @state[name] = false
    return value
  end

  def move
    reason = @simulation.move_possible?(@position, @direction)
    if reason == true
      set_state("move", true)
    else
      log("Cannot perform move() because: " + reason)
    end
  end

  def move_possible?
    reason = @simulation.move_possible?(@position, @direction)
    if reason == true
      return true
    else
      return false
    end
  end

  def evaluate
    @evaluator.evaluate
  end

  def evaluate_static
    @evaluator.evaluate_static
  end

  # This method returns an array of directions that actor can move
  def get_directions
    possible_directions = [];
    ["left", "right", "up", "down"].each do |direction|
      test_direction = Vector2.new({:direction => direction});
      if @simulation.move_possible?(self.position, test_direction) == true
        possible_directions.push(direction);
      end
    end
    return possible_directions
  end

  # This method is used by user to set direction of this Actor
  def set_direction(direction_name)
    if (direction_name == "up") || (direction_name == "down") || (direction_name == "left") || (direction_name == "right")
      new_direction = Vector2.new({:direction => direction_name});
      @direction = new_direction
    end
  end

  def get_position
    return self.position
  end

  def get_direction
    return self.direction
  end

  def marker_present?
    return @simulation.marker_present?(@position)
  end

  def pickup_marker
    if @marker.nil? && marker_present?
      set_state("pickup", true)
    end
  end

  def drop_marker
    if !@marker.nil?
      set_state("drop", true)
    end
  end

  def log(message)
    @messages << message
  end

  def get_log
    retval = @messages
    @messages = []
    return nil if (retval == [])
    return retval
  end
end

class MarkerImpl
  attr_reader :position
  attr_accessor :actor

  def initialize(position)
    @position = position
    @actor = nil
  end

  def move
    if !@actor.nil?
      @position = @actor.position
    end
  end
end

class Vector2
  attr_reader :x,:y

  def initialize(hash)
    if hash.nil?
      @x = 0
      @y = 0
    end

    if (!(hash[:x].nil?) && !(hash[:y].nil?))
      @x = hash[:x]
      @y = hash[:y]
      return
    end

    if !(hash[:direction].nil?)
      if (hash[:direction] == "left")
        @x = 0
        @y = -1
      elsif (hash[:direction] == "up")
        @x = -1
        @y = 0
      elsif (hash[:direction] == "right")
        @x = 0
        @y = 1
      elsif (hash[:direction] == "down")
        @x = 1
        @y = 0
      else
        @x = 0
        @y = 0
      end
      return
    end
  end

  def +(other_vector)
    return Vector2.new({:x => @x + other_vector.x, :y => @y + other_vector.y })
  end

  def -(other_vector)
    return Vector2.new({:x => @x - other_vector.x, :y => @y - other_vector.y })
  end

  def to_s
    return "left" if (@x == 0) && (@y == -1)
    return "up" if (@x == -1) && (@y == 0)
    return "right" if (@x == 0) && (@y == 1)
    return "down" if (@x == 1) && (@y == 0)
  end

  def zero?
    return true if (@x == 0) && (@y == 0)
    return false
  end

  def equals?(other_vector)
    return true if (@x == other_vector.x) && (@y == other_vector.y)
    return false
  end

  def get_inverse
    return Vector2.new({:direction => "right"}) if (@x == 0) && (@y == -1)
    return Vector2.new({:direction => "down"}) if (@x == -1) && (@y == 0)
    return Vector2.new({:direction => "left"}) if (@x == 0) && (@y == 1)
    return Vector2.new({:direction => "up"}) if (@x == 1) && (@y == 0)
  end
end

class Simulation < ActiveRecord::Base
  has_many :simulation_steps
  validates :name, :presence => true

  def initialized?
    return !self.simulation_steps.empty?
  end

  # Function returns true if next move is possible, reason why it is not possible otherwise
  def move_possible?(position, direction)
    new_position = position + direction
    return "collision with map edge" if (new_position.x < 0 || new_position.y < 0 || new_position.x >= @map[0].length || new_position.y >= @map.length)
    return "collision with wall" if (@map[new_position.x][new_position.y]).include?("wall")
    @actor_impls.each do |actor|
      if !actor.nil?
        if actor.position.equals?(new_position)
          return "collision with another actor named: " + actor.name
        end
      end
    end
    return true
  end

  
  def marker_present?(position)
    return false if get_markers_at(position) == []
    return true
  end

  # Gets markers from simulation at given position
  # Returns - Array of MarkerImpl objects
  #         - Empty array if no marker is present
  def get_markers_at(position)
    array = []
    @marker_impls.each do |marker|
      if (marker.position.equals?(position) && marker.actor.nil?)
        # Only add those markers that are not being carried by Actor
        array.push(marker)
      end
    end
    return array
  end

  # Removes marker from given position
  # Returns deleted marker on success, nil otherwise
  def delete_marker_at(position)
    markers = get_markers_at(position)
    if markers != []
      @marker_impls.delete(markers[0])
      return markers[0]
    else
      return nil
    end
  end

  # Puts a marker at given position
  # Returns inserted marker on success, nil otherwise
  def put_marker_at(position, marker)
    markers = get_markers_at(position)
    if (markers.length <= 4)
      @marker_impls.push(marker)
      return marker
    else
      return nil
    end
  end

  def transform(actor_impls, marker_impls)
    output = []

    # Transform all actors
    actor_impls.each do |actor_impl|
      if !actor_impl.nil?
        # Skip any holes
        actor_def = {}
        # Save actor data
        actor_def["row"] = actor_impl.position.x
        actor_def["col"] = actor_impl.position.y
        actor_def["direction"] = actor_impl.direction.to_s
        actor_def["id"] = actor_impl.id
        actor_def["type"] = "actor";

        msgs = actor_impl.get_log()

        if (!msgs.nil?)
          # Save messages if any
          actor_def["messages"] = msgs
        end

        output.push(actor_def)
      end
    end

    # Transform all markers
    marker_impls.each do |marker_impl|
      marker_def = {}
      marker_def["row"] = marker_impl.position.x
      marker_def["col"] = marker_impl.position.y
      marker_def["type"] = "marker";
      output.push(marker_def)
    end

    return output
  end

  # Main function which handles evaluating actions of actors and saves it to database
  # actors - ActorDef structure
  # initial_state - ActorMapDef structure of the starting state
  # map - Map structure of the map to simulate on
  # count - number of steps to generate
  # start - number of step to start from (0 - indicates complete generation)
  def simulate(actors, initial_state, map, count)
    unless self.initialized?
      return false
    end
    @map = map
    # Map is now created, first index is row, second col

    @actor_impls = [];
    @marker_impls = [];

    # Set actor's position according to supplied initial_state
    actors.each do |actor_def| 
      initial_state.each do |actor_map_def|

app/controllers/simulations_controller.rb
require 'json'

class SimulationsController < ApplicationController
  # GET /simulations
  # GET /simulations.xml
  def index
    @simulations = Simulation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @simulations }
    end
  end


  # GET /simulations/new
  # GET /simulations/new.xml
  def new
    @simulation = Simulation.new
    @maps = Map.all
    if @maps == []
      flash[:notice] = "Cannot create simulation without a map template. Create a map template first";
      redirect_to :action => "index"
    end
  end

  # GET /simulations/1/edit
  def edit
    @simulation = Simulation.find(params[:id])
    @maps = Map.all
  end

  # POST /simulations
  # POST /simulations.xml
  def create
    @simulation = Simulation.new(params[:simulation])
    @simulation.map_json = Map.find_by_id(params[:map][:map_id]).data

    if (params[:simulation][:name] == "")
      flash[:notice] = "Simulation must have a name."
      redirect_to :action => "index"
      return
    end
    
    if @simulation.save
      if (params[:place_actors].nil?)
        redirect_to(@simulation, :notice => 'Simulation was successfully created.')
      else
        @actors = Actor.find(:all);
        render :action => "edit_actors", :params => {:id => @simulation.id},  :locals => { :actors => @actors }
      end
    else
      render :action => "new"
    end
  end

  def edit_actors
    @actors = Actor.find(:all)
    @simulation = Simulation.find_by_id(params[:id])
  end

  def get_map
    map_json = Simulation.find_by_id(params[:simulation_id]).map_json
    respond_to do |format|
      format.json {
        render :json => { :data => map_json }
      }
    end
  end

  def get_actors
    simulation = Simulation.find_by_id(params[:id])
    actors_json = simulation.actors_json

    respond_to do |format|
      format.json {
        render :json => { :data => actors_json }
      }
    end
  end

  def get_initial_state
    simulation = Simulation.find_by_id(params[:id])
    data = {}
    data_json = nil;

    if (!simulation.nil? && simulation.initialized?)
      data["actors"] = simulation.actors_json
      data["initial_state"] = simulation.simulation_steps[0].data_json
    end

    data_json = data.to_json

    respond_to do |format|
      format.json {
        render :json => { :data => data_json }
      }
    end
  end

  def save_sim
    # Find appropriate simulation
    simulation = Simulation.find_by_id(params[:id]);
    if !simulation.nil?
      # Clear any existing steps
      simulation.simulation_steps = [];

      params[:actors].each do |actor|
        # Convert br tags into actual newlines - newline character is not being sent via AJAX
        actor[:source_code].gsub!("<br />", "\r\n")
        actor[:static_code].gsub!("<br />", "\r\n")
      end

      # Save actor data to DB
      simulation.actors_json = params[:actors].to_json

      # Create first simulation step
      simulation_step = SimulationStep.new
      simulation_step.step_no = 0;
      # Use data supplied by user as a first step
      simulation_step.data_json = params[:initialState].to_json

      simulation.simulation_steps = []
      simulation.simulation_steps << simulation_step

      simulation.save()
    end
    render :nothing => true
  end


  # PUT /simulations/1
  # PUT /simulations/1.xml
  def update
    @simulation = Simulation.find(params[:id])

    respond_to do |format|
      if @simulation.update_attributes(params[:simulation])
        format.html { redirect_to(@simulation, :notice => 'Simulation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @simulation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /simulations/1
  # DELETE /simulations/1.xml
  def destroy_it
    @simulation = Simulation.find(params[:id])
    @simulation.destroy

    respond_to do |format|
      format.html { redirect_to(simulations_url) }
      format.xml  { head :ok }
    end
  end

  def simulate
    # Get simulation from DB
    @simulation = Simulation.find_by_id(params[:id])
    @simulations = Simulation.all

    unless (@simulation.initialized?)
      flash[:notice] = "Cannot simulate unitialized simulation!"
      render :action => "index", :locals => { :simulations => @simulations }
    end

    first_step = nil
    @simulation.simulation_steps.each do |step|
      if step.step_no == 0
        first_step = step
        break
      end
    end

    @simulation.simulate(JSON.parse(@simulation.actors_json), JSON.parse(first_step.data_json), JSON.parse(@simulation.map_json), Integer(params[:count]))
    render :text => "OK"
  end

  def get_story
    story = []
    simulation_steps = Simulation.find_by_id(params[:id]).simulation_steps
    simulation_steps.sort! { |a,b| a.step_no <=> b.step_no }

    simulation_steps.each do |ss|
      story << JSON.parse(ss.data_json)
    end

    story_json = story.to_json

    render :json => { :data => story_json }
  end

  def watch
    @simulation = Simulation.find_by_id(params[:id]) 
    unless (@simulation.initialized?)
      flash[:notice] = "Cannot simulate unitialized simulation!"
      redirect_to :action => "index"
    end
  end


end

app/helpers/simulations_helper.rb
module SimulationsHelper
end

app/views/simulations/_canvas.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= javascript_include_tag 'canvas' %>

<canvas id="canvas" width="800" height="800"></canvas><br />

app/views/simulations/_form.html.erb
<%= form_for(@simulation) do |f| %>
  <% if @simulation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@simulation.errors.count, "error") %> prohibited this simulation from being saved:</h2>

      <ul>
      <% @simulation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    Map template
    <%= select "map", "map_id", @maps.map {|u| [u.name,u.id]} %>
  </div>
<div class="field">
  Immediately place actors ? <%= check_box_tag 'place_actors', 'yes', true %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/simulations/edit.html.erb
<h1>Editing simulation</h1>

<%= render 'form' %>

<%= link_to 'Back', simulations_path %>

app/views/simulations/edit_actors.html.erb
<%= javascript_include_tag 'actor-editor' %>
<%= javascript_include_tag 'jquery.contextmenu.r2.packed' %>
<%= javascript_include_tag 'jquery.simplemodal-1.4.1' %>
<%= stylesheet_link_tag 'modal' %>

<h1>Editing actors for simulation : <%= @simulation.name %></h1>
<%= render 'canvas' %>

<%= link_to 'Back', simulations_path %>

<script type="text/javascript">
    sim_id = <%= @simulation.id %>;
    load_map_for_sim();  
</script>

<div class="contextMenu" id="placeActorMenu">
      <ul>
        <li id="place">Place actor here</li>
        <li id="place_marker">Place marker here</li>
        <li id="remove">Remove actor</li>
        <li id="remove_marker">Remove marker</li>
        <li id="edit">Edit actor</li>
        <li id="save">Save</li>
      </ul>
</div>

<div class="contextMenu" id="actor-prop-content">
  <div id="prop-box">
  <h3>Actor properties</h3>
  <table>
    <tr><td>Name</td><td><%= text_field_tag "actor_name", nil, :class => "big-textbox" %></td></tr>
    <tr><td>Description</td><td><%= text_field_tag "actor_description", nil, { :disabled => "true", :class => "big-textbox" } %></td></tr>
    <tr><td>Direction</td><td><%= select_tag "actor_direction", options_for_select([["Left", "left"], ["Down", "down"], ["Up", "up"], ["Right", "right"]]) %></td></tr>
    <tr><td>Template</td><td><%= select "actor", "id", @actors.map {|u| [u.name,u.id]} %></td></tr>
  </table>
  <input id="place_btn" type="button" name="place" value="Place"></input>
  </div>
  <div id="left-box">
  <h3>Source</h3>
  <%= text_area_tag "src_preview_textarea", nil, :size => "40x24" %>
  </div>
  <div id="right-box">
  <h3>Static source</h3>
  <%= text_area_tag "sta_preview_textarea", nil, :size => "40x24" %>
  </div>
</div>

<div class="contextMenu" id="actor-edit-content">
  <div id="edit-box">
  <h3>Actor properties</h3>
  <table>
    <tr><td>Name</td><td><!--<input id="edit_actor_name" type="text" name="actor_name"></input>--><%= text_field_tag "edit_actor_name" %></td></tr>
    <tr><td>Direction</td><td><%= select_tag "edit_actor_direction", options_for_select([["Left", "left"], ["Down", "down"], ["Up", "up"], ["Right", "right"]]) %></td></tr>
  </table>
  <input id="edit_btn" type="button" name="place" value="Save"></input>
  </div>
  <div id="left-box">
  <h3>Source</h3>
  <%= text_area_tag("src_edit_textarea", nil, :size => "40x24") %>
  </div>
  <div id="right-box">
  <h3>Static source</h3>
  <%= text_area_tag("sta_edit_textarea", nil, :size => "40x24") %>
  </div>
</div>

app/views/simulations/index.html.erb
<h1>Available simulations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Computed step count</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @simulations.each do |simulation| %>
  <tr>
    <td><%= simulation.name %></td>
    <td><%= simulation.simulation_steps.length %></td>
    <td><%= link_to 'Edit actors', :controller => "simulations", :action => "edit_actors", :id => simulation.id %></td>
    <td><%= link_to 'Watch', :controller => "simulations", :action => "watch", :id => simulation.id %></td>
    <td><%= link_to 'Destroy', :controller => "simulations", :action => "destroy_it", :id => simulation.id, :confirm => "Are you sure?" %></td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'New Simulation', new_simulation_path %>

app/views/simulations/new.html.erb
<h1>Creating a new simulation</h1>

<%= render 'form' %>

<%= link_to 'Back', simulations_path %>

app/views/simulations/watch.html.erb
<%= javascript_include_tag 'simulation-player' %>
<%= javascript_include_tag 'jquery.contextmenu.r2.packed' %>
<%= javascript_include_tag 'jquery.simplemodal-1.4.1' %>
<%= stylesheet_link_tag 'modal' %>
<%= stylesheet_link_tag 'primary' %>

<script type="text/javascript">
    sim_id = <%= @simulation.id %>;
    load_map_for_sim();
</script>

<div id="player-canvas">
<h1>Watching simulation: <%= @simulation.name %></h1>
<%= render 'canvas' %>
<%= link_to 'Back', simulations_path %> |
<%= link_to 'Edit actors', :action => "edit_actors", :id => @simulation.id %>
</div>

<div id="player-tools">
<h1>Messages</h1>
<%= text_area_tag "messages_textarea", nil, { :size => "40x24", :disabled => true } %><br />
<h1>Playback control</h1>
Step<%= number_field_tag 'step_ctrl', nil, :class => "step-textbox" %> of <%= number_field_tag 'step_end', nil, :class => "step-textbox" %>
<input id="btn_step_up" type="button" value="+"></input><input id="btn_step_down" type="button" name="btn" value="-"></input><input id="btn_simulate" type="button" name="btn" value="Simulate..."></input><br />
<input id="chk_autoplay" type="checkbox">AutoPlay</input><br />
</div>

<div class="contextMenu" id="contextMenu">
      <ul>
        <li id="show_source">Show source code</li>
        <li id="show_static">Show static source code</li>
      </ul>
</div>

<div class="contextMenu" id="source-show-content">
  <h3 id="src_label">Source</h3>
  <%= text_area_tag "src_textarea", nil, { :size => "80x24", :disabled => true } %>
</div>

<div class="contextMenu" id="simulate-content">
  <h3 id="simulate_label">Enter number of steps you want to simulate</h3>
  <%= number_field_tag "step_count" %>
  <input id="btn_simulate_confirm" type="button" name="btn" value="Simulate"></input>
</div>