config/routes.rb
RobotKarel::Application.routes.draw do
  resources :actors
  resources :simulations
  resources :maps

  match 'maps/:id/get_map' => 'maps#get_map'
  match 'maps/:id/save_map' => 'maps#save_map'
  match 'simulations/:simulation_id/get_map' => 'simulations#get_map'
  match 'simulations/:id/place_actors' => 'simulation#place_actors'
  match 'simulations/:id/save_sim' => 'simulations#save_sim'
  match 'simulations/:id/:count/simulate' => 'simulations#simulate'
  match 'simulations/:id/get_story' => 'simulations#get_story'
  match 'simulations/:id/watch' => 'simulations#watch'
  match 'simulations/:id/get_initial_state' => 'simulations#get_initial_state'
  match 'simulations/:id/get_actors' => 'simulations#get_actors'
  match 'actors/:id/get_properties' => 'actors#get_properties'

  match '/' => 'help#welcome'

  match ':controller(/:action(/:id(.:format)))'
end

app/models/actor.rb
class Actor < ActiveRecord::Base
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  # GET /actors
  # GET /actors.xml
  def index
    @actors = Actor.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @actors }
    end
  end

  # GET /actors/1
  # GET /actors/1.xml
  def show
    @actor = Actor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @actor }
    end
  end

  # GET /actors/new
  # GET /actors/new.xml
  def new
    @actor = Actor.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @actor }
    end
  end

  # GET /actors/1/edit
  def edit
    @actor = Actor.find(params[:id])
  end

  # POST /actors
  # POST /actors.xml
  def create
    @actor = Actor.new(params[:actor])

    respond_to do |format|
      if @actor.save
        format.html { redirect_to(@actor, :notice => 'Actor was successfully created.') }
        format.xml  { render :xml => @actor, :status => :created, :location => @actor }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @actor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /actors/1
  # PUT /actors/1.xml
  def update
    @actor = Actor.find(params[:id])

    respond_to do |format|
      if @actor.update_attributes(params[:actor])
        format.html { redirect_to(@actor, :notice => 'Actor was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @actor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.xml
  def destroy_it
    @actor = Actor.find(params[:id])
    @actor.destroy

    respond_to do |format|
      format.html { redirect_to(actors_url) }
      format.xml  { head :ok }
    end
  end


  def get_properties
    actor = Actor.find_by_id(params[:id])
    data = {}
    data["source_code"] = actor.source_code
    data["static_code"] = actor.static_code
    data["description"] = actor.description

    render :json => { :data => data.to_json }
  end


end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/views/actors/_form.html.erb
<%= form_for(@actor) do |f| %>
  <% if @actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% @actor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :source_code %><br />
    <%= f.text_area :source_code, :size => "80x20" %>
  </div>
  <div class="field">
    <%= f.label :static_code %><br />
    <%= f.text_area :static_code, :size => "80x20"%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing actor template</h1>

<%= render 'form' %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<h1>Available actor templates</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @actors.each do |actor| %>
  <tr>
    <td><%= actor.name %></td>
    <td><%= actor.description %></td>
    <td><%= link_to 'Show', actor %></td>
    <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
    <td><%= link_to 'Destroy', :action => "destroy_it", :id => actor.id %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Actor', new_actor_path %>

app/views/actors/new.html.erb
<h1>Creating a new actor template</h1>

<%= render 'form' %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p>
  <b>Name:</b>
  <%= @actor.name %>
</p>

<p>
  <b>Description:</b>
  <%= @actor.name %>
</p>

<p>
  <b>Source code:</b><br />
  <%= text_area_tag("source_code", @actor.source_code, :size => "80x20", :disabled => true) %>
</p>

<p>
  <b>Static code:</b><br />
  <%= text_area_tag("source_code", @actor.static_code, :size => "80x20", :disabled => true) %>
</p>

<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>