config/routes.rb
RobotKarel::Application.routes.draw do
  resources :actors
  resources :simulations
  resources :maps

  match 'maps/:id/get_map' => 'maps#get_map'
  match 'maps/:id/save_map' => 'maps#save_map'
  match 'simulations/:simulation_id/get_map' => 'simulations#get_map'
  match 'simulations/:id/place_actors' => 'simulation#place_actors'
  match 'simulations/:id/save_sim' => 'simulations#save_sim'
  match 'simulations/:id/:count/simulate' => 'simulations#simulate'
  match 'simulations/:id/get_story' => 'simulations#get_story'
  match 'simulations/:id/watch' => 'simulations#watch'
  match 'simulations/:id/get_initial_state' => 'simulations#get_initial_state'
  match 'simulations/:id/get_actors' => 'simulations#get_actors'
  match 'actors/:id/get_properties' => 'actors#get_properties'

  match '/' => 'help#welcome'

  match ':controller(/:action(/:id(.:format)))'
end

app/models/map.rb
class Map < ActiveRecord::Base
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  # GET /maps
  # GET /maps.xml
  def index
    @maps = Map.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /maps/1
  # GET /maps/1.xml
  def show
    @map = Map.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /maps/new
  # GET /maps/new.xml
  def new
    @map = Map.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /maps/1/edit
  def edit
    @map = Map.find(params[:id])
  end

  # POST /maps
  # POST /maps.xml
  def create
    valid = true
    @map = nil
    begin
      valid = false if params[:size] == ""
      size = params[:size].to_i
      valid = false if (size < 0) || (size > 30)
      valid = false if (params[:map][:name] == "")
    rescue Exception => e
      valid = false
    end

    if valid
      @map = Map.new(params[:map])
      # prepare empty JSON data
      map = Array.new(params[:size].to_i) { Array.new(params[:size].to_i, []) }
      @map.data = map.to_json
      @map.save
    end

    respond_to do |format|
      if valid
        flash[:notice] = "Map successfully created"
        format.html { redirect_to :action => "edit", :id => @map.id }
      else
        flash[:notice] = "Cannot create map (wrong dimensions ?)"
        format.html { redirect_to :action => "index" }
      end
    end
  end

  # PUT /maps/1
  # PUT /maps/1.xml
  def update
    @map = Map.find(params[:id])

    respond_to do |format|
      if @map.update_attributes(params[:map])
        format.html { redirect_to(@map, :notice => 'Map was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.xml
  def destroy_it
    @map = Map.find(params[:id])
    @map.destroy

    respond_to do |format|
      format.html { redirect_to(maps_url) }
    end
  end

  # GET maps/1/get_map
  def get_map
    @map = Map.find(params[:id])
    render :json => { :data => @map.data }
  end

  def save_map    
    @map = Map.find(params[:id])
    @map.data = params[:_json].to_json
    @map.save()
    render :text => "OK"
  end
  
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_canvas.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= javascript_include_tag 'canvas' %>

<canvas id="canvas" width="800" height="800"></canvas><br />

app/views/maps/_form.html.erb
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Map name<br />
    <%= f.text_field :name, :class => "small-textbox" %>
  </div>

  <div class="field">
    Map dimensions (width and height)<br />
    <%= text_field_tag :size, nil, :class => "small-textbox" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<%= javascript_include_tag 'map-editor' %>
<%= javascript_include_tag 'jquery-ui-1.8.10.custom.min' %>
<%= javascript_include_tag 'json2' %>
<%= javascript_include_tag 'jquery.contextmenu.r2.packed' %>

<h1>Editing map template : <%= @map.name %></h1>

<%= render 'canvas' %>

<script type="text/javascript">
    map_id = <%= @map.id %>;
    load_map();
</script>

<div class="contextMenu" id="toolSelectMenu">
      <ul>
        <li id="wall">Select brush wall</li>
        <li id="eraser">Select eraser</li>
        <li id="save">Save</li>
      </ul>
</div>

<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<h1>Available map templates</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @maps.each do |map| %>
  <tr>
    <td><%= map.name %></td>
    <td><%= link_to 'Show', map %></td>
    <td><%= link_to 'Edit', edit_map_path(map) %></td>
    <td><%= link_to 'Destroy', :controller => "maps", :action => "destroy_it", :id => map.id %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Map', new_map_path %>

app/views/maps/new.html.erb
<h1>Creating a new map template</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<%= javascript_include_tag 'map-display' %>

<h1>Displaying map: <%= @map.name %></h1>

<%= render 'canvas' %>

<script type="text/javascript">
    map_id = <%= @map.id %>;
    load_map();
</script>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>